name: Bug Report
description: Create a report to help us improve
labels: [bug]
body:
  - type: dropdown
    id: widget_package
    attributes:
      label: Which at_widget package you find issue with?
      multiple: true
      options:
        - at_backupkey_flutter
        - at_chat_flutter
        - at_common_flutter
        - at_contacts_flutter
        - at_contacts_group_flutter
        - at_events_flutter
        - at_follows_flutter
        - at_invitation_flutter
        - at_location_flutter
        - at_login_flutter
        - at_notify_flutter
        - at_onboarding_flutter
        - at_sync_ui_flutter
        - at_theme_flutter
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: On what platforms did you experience the issue?
      multiple: true
      options:
        - Android
        - iOS
        - Windows
        - MacOS
        - Linux
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: What version are you using?
      placeholder: 'package : version'
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Description of the bug.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1. Go to '...'
        2. Run '...'
        3. Create '...'
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Additional info
      placeholder: Please add any relevant code, screenshots and info needed to reproduce this issue.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      placeholder: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: console
  - type: textarea
    id: flutter-analyze
    attributes:
      label: Flutter analyze output
      description: Paste the output of `flutter analyze` here, if you are developing.
      placeholder: If there are any analysis errors, try resolving them before filing this issue.
      render: console
  - type: textarea
    id: flutter-doctor
    attributes:
      label: Flutter doctor output
      description: Paste the output of `flutter doctor -v` here, If you are developing.
      render: console
