include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_local_variable: warning
    invalid_assignment: warning
    missing_return: error
    annotate_overrides: error
    always_specify_types: warning
    dead_code: warning
    todo: ignore
  exclude: [build/**]

linter:
  rules:
    - camel_case_types
    - unnecessary_statements