name: at_app_flutter
description: A library that help developers build flutter applications on the @platform.
version: 2.0.0
repository: https://github.com/atsign-foundation/at_widgets
homepage: https://atsign.dev/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  at_client_mobile: ^3.0.3
  at_onboarding_flutter: ^3.0.1
  at_utils: ^3.0.0
  dotenv: ^3.0.0
  path_provider: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
